# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: e2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x65\x32.proto\x12\x0b\x45\x32_protobuf\"%\n\rSimpleMessage\x12\x14\n\x0clucky_number\x18\x01 \x02(\x05\"\x1c\n\nE2_request\x12\x0e\n\x06req_id\x18\x01 \x02(\r\"H\n\x11\x45\x32_dummy_response\x12\x0e\n\x06req_id\x18\x01 \x02(\r\x12\x13\n\x0bmess_string\x18\x02 \x02(\t\x12\x0e\n\x06result\x18\x03 \x02(\x08\"5\n\rgnbIndication\x12\x0e\n\x06gnb_id\x18\x01 \x02(\t\x12\x14\n\x0cgeneral_mess\x18\x02 \x02(\t')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'e2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLEMESSAGE._serialized_start=25
  _SIMPLEMESSAGE._serialized_end=62
  _E2_REQUEST._serialized_start=64
  _E2_REQUEST._serialized_end=92
  _E2_DUMMY_RESPONSE._serialized_start=94
  _E2_DUMMY_RESPONSE._serialized_end=166
  _GNBINDICATION._serialized_start=168
  _GNBINDICATION._serialized_end=221
# @@protoc_insertion_point(module_scope)
